server:
  error:
    include-message: always
    include-binding-errors: always


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/amigoscode
    username: root
    password: rootroot
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
